version: '3.5'
services:
  postgres:
    image: postgres:16.1-alpine3.19
    command: postgres -c 'max_connections=300' -c 'log_error_verbosity=terse'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rinha
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '200MB'

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1